behaviors:
  SeekerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      curiosity:
        strength: 0.1
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 3
        learning_rate: 0.0003
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 2000
